{
  "hash": "ce51d610d17162c7b0fdd4f38639f25e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to ReproducibleYostIndex\"\nauthor: \" Rafael Catoia Pulgrossi | [QSU](https://med.stanford.edu/qsu 'View website') | [Tae Yoon Lee](https://profiles.stanford.edu/tae-yoon-lee 'View website') | [Summer Han](https://med.stanford.edu/summerhanlab.html 'View website')\"\ndate: today\nformat:\n  html:\n    self-contained: true\n    theme: united\n    toc: true\n    toc-expand: 4\n    toc-depth: 4\n    code-fold: true\n    toc-title: 'Contents'\n    page-layout: full\n    grid:\n      body-width: 1440px\n      gutter-width: 1.5rem\nexecute:\n  freeze: true\neditor_options:\n  chunk_output_type: console\n---\n\n\n\n## Social Determinants of Health\n\nSocial determinants of health (SDOH) are the conditions in which people are born, grow, live, work, and age. These circumstances are shaped by the distribution of money, power, and resources at global, national, and local levels. Research has consistently shown that SDOH have a profound impact on health outcomes, often accounting for more variation in health than medical care alone.\n\nKey domains of SDOH include:\n\n- **Economic Stability**: Employment, income, expenses, debt, and financial support\n- **Education Access and Quality**: Educational attainment, literacy, language, and early childhood education\n- **Healthcare Access and Quality**: Insurance coverage, access to primary care, and health literacy\n- **Neighborhood and Built Environment**: Housing quality, transportation, safety, parks, and walkability\n- **Social and Community Context**: Social cohesion, civic participation, discrimination, and incarceration\n\nUnderstanding and measuring SDOH is critical for health research and intervention. Neighborhood-level socioeconomic status (SES) is one of the most important social determinants, as it captures the collective effect of multiple socioeconomic factors that influence health behaviors, access to resources, and exposure to environmental hazards.\n\n## The Yost Index: A Composite Measure of Neighborhood SES\n\nThe Yost Index is a validated, composite measure of neighborhood-level socioeconomic status developed by cancer researchers to study the relationship between SES and cancer outcomes (Yost et al., 2001). Unlike single indicators such as median income or poverty rates, the Yost Index combines multiple socioeconomic variables to provide a more comprehensive and nuanced measure of neighborhood disadvantage.\n\n### The Seven Component Variables\n\nThe Yost Index is constructed from seven key socioeconomic indicators derived from the U.S. Census Bureau's American Community Survey (ACS):\n\n1. **Median household income** (`income`)\n2. **Percent working class** (`wkcls`): Proportion of employed persons in working-class occupations\n3. **Unemployment rate** (`unemp`): Percent of civilians in the labor force who are unemployed\n4. **Educational attainment** (`educ`): Percent with less than high school education (age 25+)\n5. **Poverty rate** (`poverty150`): Percent of persons below 150% of the federal poverty line\n6. **Median rent** (`rent`): Median gross rent for renter-occupied housing units\n7. **Median home value** (`hval`): Median value of owner-occupied housing units\n\n### How the Yost Index is Calculated\n\nThe `ReproducibleYostIndex` package automates the entire process of calculating the Yost Index:\n\n1. **Data Retrieval**: Fetches the necessary ACS variables (estimates and margins of error) via the `tidycensus` package\n2. **Variable Calculation**: Computes the seven component variables from raw ACS estimates\n3. **Stabilization** *(optional)*: Reduces small-area estimation noise by pulling unreliable lower-level estimates (e.g., block groups) toward their parent geography (e.g., tract), weighted by sampling variance from the ACS margins of error\n4. **Missing Data Imputation** *(optional)*: Performs spatial imputation for missing values using neighboring geographies\n5. **Standardization**: Rescales variables (by ranking or standardizing) to put them on a comparable scale\n6. **Factor Analysis**: Extracts a single underlying factor representing neighborhood SES\n7. **Quintile Assignment**: Divides the continuous Yost scores into quintiles for easy interpretation\n\nThe resulting Yost Index is a continuous measure where higher values indicate higher socioeconomic status. Quintiles (1 = lowest SES, 5 = highest SES) provide a categorical version for stratified analyses.\n\n### Why Use the Yost Index?\n\nThe Yost Index offers several advantages over simpler SES measures:\n\n- **Comprehensiveness**: Captures multiple dimensions of socioeconomic disadvantage\n- **Validation**: Extensively used in epidemiological research, particularly cancer studies\n- **Comparability**: Standardized approach allows for comparisons across studies and geographic areas\n- **Flexibility**: Can be calculated at various geographic levels (county, tract, block group) and scopes (national, state)\n- **Handling Missing Data**: Built-in spatial imputation methods address incomplete data\n- **Small-Area Stabilization**: Optional stabilization estimation reduces noise in unreliable small-area estimates by borrowing strength from parent geographies, particularly valuable for block group analyses where ACS margins of error can be very large\n\n## Getting Yost Index Data with `getYostIndex()`\n\nThe recommended way to obtain Yost Index values is `getYostIndex()` — a fast, Census-API-free function that downloads pre-computed results directly from the [ReproducibleYostIndex-data](https://github.com/HanLabCollaboration/ReproducibleYostIndex-data) GitHub repository.\n\n### Pre-computation and Data Release\n\nTo make the Yost Index immediately accessible without requiring a Census API key or computation time, we pre-computed all four Yost variants for every geography × scope × year combination using a SLURM batch pipeline on a high-performance computing cluster. The results are published as release assets on GitHub under the tag **`data-v2026.04`**.\n\n#### Computation Details\n\nEach pre-computed file was produced using the following pipeline:\n\n- **Ranking**: Each of the seven Yost component variables is ranked across all GEOIDs within the scope pool (national or state) before factor analysis. Ranking places all variables on a common, interpretable scale and harmonizes scores across GEOIDs regardless of ACS year or geographic vintage.\n- **Factor analysis**: Performed using the `psych` R package (Maximum Likelihood extraction, oblimin rotation), retaining a single latent factor to represent the Yost Index.\n- **Scope** controls which pool of geographies is used for ranking and quintile assignment:\n  - `scope = \"national\"` — all geographies across the entire United States are ranked together. A quintile of 5 means a neighborhood is among the most deprived 20% **nationally**. This is the appropriate choice for studies comparing areas across states.\n  - `scope = \"state\"` — geographies are ranked **within each state separately**. A quintile of 5 means the neighborhood is among the most deprived 20% **within its state**. This removes between-state variation and is preferred when the research question is about relative deprivation within a state.\n- **Four variants** are always pre-computed and returned together: baseline (`Yost`), empirical Bayes–stabilized (`YostStabilized`), missing-value imputed (`YostImputed`), and stabilized + imputed (`YostStabilizedImputed`).\n\n#### Available Files\n\n| Geography | Scope | Years |\n|---|---|---|\n| County | National, State | 2011–2024 |\n| Tract | National, State | 2011–2024 |\n| Block group | National, State | 2013–2024 |\n\n> **Coverage note:** Pre-computed files currently cover ACS 5-year estimates through **2024**. Data for 2025 will be added once the US Census Bureau releases the 2025 ACS 5-year estimates (typically December of the following year).\n\nTwo file types are available per combination:\n\n- **74 CSV files** (`.csv.gz`): one per geography × scope × year, containing all four Yost variants in a single wide table\n- **37 GeoPackage files** (`.gpkg`): one per geography × year (scope-agnostic), containing Census boundaries for mapping\n\nFiles are cached locally after the first download so subsequent calls with the same arguments are instantaneous.\n\n### `getYostIndex()` Options\n\n```r\ngetYostIndex(\n  geo      = \"tract\",        # \"county\", \"tract\", \"block group\" (or \"cbg\"), \"state\"\n  year     = 2022,           # ACS 5-year estimate year (2011–2024; block group: 2013–2024)\n  states   = NULL,           # character vector of state abbreviations, e.g. c(\"CA\", \"NY\")\n  scope    = \"national\",     # \"national\" or \"state\"\n  geometry = FALSE,          # TRUE returns an sf object with Census boundaries attached\n  cache    = TRUE,           # FALSE forces a fresh download (bypasses local cache)\n  quiet    = FALSE           # TRUE suppresses all download messages\n)\n```\n\nThe function returns a tibble (or `sf` object when `geometry = TRUE`) with columns:\n\n| Column | Description |\n|---|---|\n| `GEOID` | Census geographic identifier |\n| `year`, `geo`, `scope` | Parameters used |\n| `Yost`, `YostQuintile` | Baseline Yost Index |\n| `YostStabilized`, `YostStabilizedQuintile` | Empirical Bayes–stabilized |\n| `YostImputed`, `YostImputedQuintile` | Missing-value imputed |\n| `YostStabilizedImputed`, `YostStabilizedImputedQuintile` | Stabilized + imputed |\n\nAll four variants are always returned in a single call — no need to recompute for different configurations.\n\n### Quick Examples\n\nThe three calls below illustrate the most common use patterns. All return a tibble with all four Yost variants — no Census API key required. Files are cached locally after the first download, so repeat calls are instantaneous.\n\n- **Counties** (`geo = \"county\"`) are the coarsest geography and fastest to download. National scope is the default, ranking all US counties together.\n- **Tracts** (`geo = \"tract\"`) offer finer resolution. Passing `states` restricts the download to the requested states; `scope = \"state\"` re-ranks geographies within each state separately, removing between-state variation.\n- **Block groups** (`geo = \"block group\"`) provide the highest spatial resolution available. Setting `geometry = TRUE` attaches Census boundary polygons, returning an `sf` object ready for mapping.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ReproducibleYostIndex)\n\n# All US counties, 2022 — no Census API key needed\ncounty_yost <- getYostIndex(geo = \"county\", year = 2022)\n\n# Tracts for California and New York, state-level quintiles\ntracts <- getYostIndex(\n  geo    = \"tract\",\n  year   = 2022,\n  states = c(\"CA\", \"NY\"),\n  scope  = \"state\"\n)\n\n# Block groups with geometry attached for direct mapping\nbg_sf <- getYostIndex(\n  geo      = \"block group\",\n  year     = 2021,\n  states   = \"CA\",\n  geometry = TRUE\n)\n```\n:::\n\n\nThe maps below show the Yost Stabilized + Imputed quintile (`YostStabilizedImputedQuintile`) across three geographies simultaneously — from the national county-level picture down to Manhattan block groups — using the 2022 ACS and national scope throughout.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ReproducibleYostIndex)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(sf)\nlibrary(patchwork)\n\n# --- Data -------------------------------------------------------------------\nus_counties <- getYostIndex(geo = \"county\",      year = 2022,\n                            geometry = TRUE, quiet = TRUE)\n\nca_tracts   <- getYostIndex(geo = \"tract\",       year = 2022,\n                            states = \"CA\", geometry = TRUE, quiet = TRUE)\n\nmn_bg       <- getYostIndex(geo = \"block group\", year = 2022,\n                            states = \"NY\", geometry = TRUE, quiet = TRUE) |>\n  dplyr::filter(startsWith(GEOID, \"36061\"))   # New York County (Manhattan)\n\n# --- Shared palette ---------------------------------------------------------\nquintile_colors <- c(\n  \"1\" = \"#e0f3db\",\n  \"2\" = \"#a8ddb5\",\n  \"3\" = \"#7bccc4\",\n  \"4\" = \"#43a2ca\",\n  \"5\" = \"#0868ac\"\n)\n\nmake_map <- function(data, title, subtitle = NULL, linewidth = 0.1) {\n  data <- data |>\n    dplyr::mutate(q = factor(YostStabilizedImputedQuintile, levels = 1:5))\n\n  ggplot(data) +\n    geom_sf(aes(fill = q), color = \"grey80\", linewidth = linewidth) +\n    scale_fill_manual(\n      values       = quintile_colors,\n      name         = \"Quintile\",\n      labels       = c(\"1\", \"2\", \"3\", \"4\", \"5\"),\n      drop         = FALSE,\n      na.value     = \"white\",\n      na.translate = FALSE,\n      guide        = guide_legend(override.aes = list(linewidth = 0.2, color = \"white\"))\n    ) +\n    labs(title = title, subtitle = subtitle) +\n    theme_void(base_size = 11) +\n    theme(\n      plot.title    = element_text(face = \"bold\", size = 13, hjust = 0.5),\n      plot.subtitle = element_text(size = 9, hjust = 0.5, color = \"grey40\"),\n      legend.position = \"bottom\",\n      legend.title  = element_text(size = 9),\n      legend.text   = element_text(size = 8)\n    )\n}\n\n# --- Plot 1: US Counties (CONUS, Albers projection) -------------------------\np1 <- us_counties |>\n  dplyr::filter(!startsWith(GEOID, \"02\"),    # drop Alaska\n                !startsWith(GEOID, \"15\"),    # drop Hawaii\n                !startsWith(GEOID, \"72\")) |> # drop Puerto Rico\n  make_map(\n    title     = \"US Counties\",\n    subtitle  = \"Yost Stabilized + Imputed | 2022 ACS | National Scope\",\n    linewidth = 0.05\n  ) +\n  coord_sf(crs = \"+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96\")\n\n# --- Plot 2: California Tracts ----------------------------------------------\np2 <- make_map(\n  ca_tracts,\n  title     = \"California Census Tracts\",\n  subtitle  = \"Yost Stabilized + Imputed | 2022 ACS | National Scope\",\n  linewidth = 0.05\n)\n\n# --- Plot 3: Manhattan Block Groups -----------------------------------------\np3 <- make_map(\n  mn_bg,\n  title     = \"Manhattan Block Groups\",\n  subtitle  = \"Yost Stabilized + Imputed | 2022 ACS | National Scope\",\n  linewidth = 0.15\n)\n\n# --- Combine with single shared legend --------------------------------------\ncombined <- (p1 + p2 + p3) +\n  plot_layout(ncol = 3, widths = c(1, 1, 1), guides = \"collect\") &\n  theme(legend.position = \"bottom\")\n\ncombined + plot_annotation(\n  title = \"Neighborhood Socioeconomic Status — Yost Index\",\n  theme = theme(plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5))\n)\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/getYostIndex_maps-1.png){fig-align='center' width=1536}\n:::\n:::\n\n\n#### Baseline vs. Stabilized + Imputed: San Mateo County Tracts\n\nThe four Yost variants returned by `getYostIndex()` differ in whether stabilization and spatial imputation are applied. The comparison below focuses on the impact of the imputation step on the availability of Yost Index values at the block group level, where ACS data are often sparse. \n\n- **Yost Index**: raw factor scores, ranked across all census block groups. Block groups with sparse ACS data or missing values will have missing quintiles (shown in white).\n\n- **Yost Index Stabilized + Imputed**: estimates are first pulled toward their parent tract/county mean using ACS margins of error (stabilization), and any remaining missing values are filled from neighboring geographies (imputation). This version is recommended for analyses where data completeness and small-area reliability matter.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\n# San Mateo County tracts, national scope, with geometry\nsan_mateo <- getYostIndex(\n  geo      = \"cbg\",\n  year     = 2022,\n  states   = \"CA\",\n  scope    = \"national\",\n  geometry = TRUE,\n  quiet    = TRUE\n) \n\nquintile_colors <- c(\n  \"1\" = \"#e0f3db\",\n  \"2\" = \"#a8ddb5\",\n  \"3\" = \"#7bccc4\",\n  \"4\" = \"#43a2ca\",\n  \"5\" = \"#0868ac\"\n)\n\nmake_map_col <- function(data, col, title) {\n  data <- data |>\n    dplyr::mutate(q = factor(.data[[col]], levels = 1:5))\n\n  ggplot(data) +\n    geom_sf(aes(fill = q), color = \"grey80\", linewidth = 0.2) +\n    scale_fill_manual(\n      values       = quintile_colors,\n      name         = \"Quintile\",\n      labels       = c(\"1\", \"2\", \"3\", \"4\", \"5\"),\n      drop         = FALSE,\n      na.value     = \"white\",\n      na.translate = FALSE\n    ) +\n    labs(title = title,\n         subtitle = \"2022 ACS 5-Year Estimates | Census Block Groups\") +\n    theme_void() +\n    theme(\n      plot.title    = element_text(face = \"bold\", size = 13, hjust = 0.5),\n      plot.subtitle = element_text(size = 9, hjust = 0.5, color = \"grey40\"),\n      legend.title  = element_text(size = 9),\n      legend.text   = element_text(size = 8)\n    )\n}\n\np_base <- make_map_col(san_mateo, \"YostQuintile\",                  \"Yost Index\")\np_stab <- make_map_col(san_mateo, \"YostStabilizedImputedQuintile\", \"Yost Index (Stabilized + Imputed)\")\n\n(p_base + p_stab) +\n  plot_layout(guides = \"collect\") &\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/imputed_comparison-1.png){fig-align='center' width=1536}\n:::\n:::\n\n\n---\n\n## Why the Yost Index Matters: A Confounding Example\n\nOne of the most important uses of the Yost Index in health research is to control for socioeconomic confounding. Consider a study examining the relationship between environmental exposure (e.g., air pollution) and a health outcome (e.g., asthma prevalence). Both environmental exposures and health outcomes are often strongly associated with neighborhood SES:\n\n- Low-SES neighborhoods may have higher pollution exposure due to proximity to highways, industrial areas, or lack of green space\n- Low-SES neighborhoods may also have higher asthma rates due to factors like housing quality, access to healthcare, stress, and other SDOH\n\n**If we don't account for neighborhood SES, we might incorrectly attribute health effects to environmental exposure when they are actually driven (in whole or in part) by socioeconomic factors.**\n\nLet's demonstrate this with a simulated example using real Yost Index data for California census tracts.\n\n### Setup\n\nFirst, load the required packages:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ReproducibleYostIndex)\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Set seed for reproducibility\nset.seed(42)\n```\n:::\n\n\n### Step 1: Get the Yost Index for California\n\nWe retrieve pre-computed Yost Index values for all California census tracts (2022 ACS, state scope) using `getYostIndex()`. No Census API key required.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nyost_ca <- getYostIndex(\n  geo    = \"tract\",\n  year   = 2022,\n  states = \"CA\",\n  scope  = \"state\"\n)\n\ndf_ca <- yost_ca\n```\n:::\n\n\nNow we have Yost Index values for all California tracts. Let's visualize their spatial distribution using `geometry = TRUE`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Download with geometry attached (cached after first call)\nyost_ca_sf <- getYostIndex(\n  geo      = \"tract\",\n  year     = 2022,\n  states   = \"CA\",\n  scope    = \"state\",\n  geometry = TRUE,\n  quiet    = TRUE\n)\n\nggplot(yost_ca_sf) +\n  geom_sf(aes(fill = YostImputed), color = \"white\", size = 0.05) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    name = \"Yost Index\",\n    guide = guide_colorbar(\n      barwidth = 1,\n      barheight = 15,\n      title.position = \"top\",\n      title.hjust = 0.5\n    )\n  ) +\n  labs(\n    title    = \"Neighborhood Socioeconomic Status in California\",\n    subtitle = \"Yost Index (Imputed) | 2022 ACS 5-Year Estimates | State Scope\",\n    caption  = \"Higher values indicate higher socioeconomic status\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title    = element_text(face = \"bold\", size = 16, hjust = 0.5),\n    plot.subtitle = element_text(size = 12, hjust = 0.5, color = \"grey30\"),\n    plot.caption  = element_text(size = 9, hjust = 0.5, color = \"grey50\", margin = margin(t = 10)),\n    legend.position = \"right\",\n    plot.margin = margin(20, 20, 20, 20)\n  )\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/display_yost-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n### Step 2: Simulate an Environmental Exposure\n\nNow, let's simulate an environmental exposure (e.g., air pollution PM2.5 levels) that is correlated with neighborhood SES. Lower-SES neighborhoods tend to have higher exposure due to proximity to highways, industrial areas, and other pollution sources:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulate pollution exposure (higher in low-SES neighborhoods)\n# The Yost Index is scaled so higher = higher SES (range 8-12)\n# We'll create pollution that decreases as Yost increases\n\ndf_ca <- df_ca %>%\n  mutate(\n    # Base pollution inversely related to Yost quintile + random variation\n    # Q1 (lowest SES) has highest pollution, Q5 (highest SES) has lowest\n    pollution_base = 14 - 1.2 * as.numeric(YostImputedQuintile) + rnorm(n(), mean = 0, sd = 1.5),\n    # Ensure realistic PM2.5 values (typically 5-20 µg/m³ in CA)\n    pollution = pmax(pollution_base, 5)\n  )\n```\n:::\n\n\n### Step 3: Simulate a Health Outcome\n\nNext, we simulate asthma prevalence in children. Crucially, we'll make asthma depend on **both** pollution exposure **and** neighborhood SES (through pathways other than pollution, such as housing quality, healthcare access, and stress):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulate childhood asthma prevalence (%)\n# True model: asthma is caused by BOTH pollution AND low SES\n\n# Define the true effects by quintile\n# Q1 = lowest SES (highest risk), Q5 = highest SES (lowest risk)\nses_effect <- c(8.0, 5.0, 3.0, 1.5, 0)  # % increase in asthma by quintile\npollution_effect <- 0.4  # 0.4% increase per µg/m³ of PM2.5\n\ndf_ca <- df_ca %>%\n  mutate(\n    # Baseline asthma rate + SES effect + pollution effect + random variation\n    asthma_pct =\n      6.5 +                                               # Baseline (Q5, no pollution)\n      ses_effect[YostImputedQuintile] +                   # SES effect by quintile\n      pollution_effect * (pollution - 8) +                # Pollution effect (centered at 8)\n      rnorm(n(), mean = 0, sd = 1.2),                     # Random noise\n\n    # Keep asthma rates realistic (0-25%)\n    asthma_pct = pmax(pmin(asthma_pct, 25), 0)\n  )\n```\n:::\n\n\nIn this simulation, the **true causal structure** is:\n\n- **SES effect**: Children in Q1 (lowest SES) have 8% higher asthma rates than Q5 (highest SES), independent of pollution\n- **Pollution effect**: Each 1 µg/m³ increase in PM2.5 increases asthma by 0.4%, independent of SES\n- **Confounding**: Low-SES neighborhoods (Q1) have ~6 µg/m³ more pollution than high-SES neighborhoods (Q5)\n\n### Step 4: Visualize the Confounding Structure\n\nBefore running models, let's visualize how pollution varies by SES quintile:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate mean pollution and asthma by quintile\nquintile_summary <- df_ca %>%\n  group_by(YostImputedQuintile) %>%\n  summarise(\n    mean_pollution = mean(pollution),\n    mean_asthma = mean(asthma_pct),\n    .groups = \"drop\"\n  )\n\n# Create side-by-side plots\np1 <- ggplot(quintile_summary, aes(x = factor(YostImputedQuintile), y = mean_pollution)) +\n  geom_col(fill = \"coral\") +\n  labs(\n    title = \"Pollution by SES Quintile\",\n    x = \"Yost Quintile\\n(1=Lowest SES, 5=Highest SES)\",\n    y = \"Mean PM2.5 (µg/m³)\"\n  ) +\n  theme_minimal()\n\np2 <- ggplot(quintile_summary, aes(x = factor(YostImputedQuintile), y = mean_asthma)) +\n  geom_col(fill = \"steelblue\") +\n  labs(\n    title = \"Asthma by SES Quintile\",\n    x = \"Yost Quintile\\n(1=Lowest SES, 5=Highest SES)\",\n    y = \"Mean Asthma Rate (%)\"\n  ) +\n  theme_minimal()\n\ngridExtra::grid.arrange(p1, p2, ncol = 2)\n#> Warning: Removed 1 row containing missing values or values outside the scale range\n#> (`geom_col()`).\n#> Removed 1 row containing missing values or values outside the scale range\n#> (`geom_col()`).\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/confounding_viz-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n**Key observation**: Both pollution exposure AND asthma rates are higher in lower-SES neighborhoods. This is the confounding structure we need to account for.\n\n### Step 5: Naive Analysis (Without Adjusting for SES)\n\nLet's first examine the relationship between pollution and asthma **without** controlling for neighborhood SES:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Naive model: asthma ~ pollution only\nmodel_naive <- lm(asthma_pct ~ pollution, data = df_ca)\nsummary(model_naive)\n#> \n#> Call:\n#> lm(formula = asthma_pct ~ pollution, data = df_ca)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -7.9024 -1.5375 -0.0987  1.4687  8.0733 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) -2.65353    0.10962  -24.21   <2e-16 ***\n#> pollution    1.30909    0.01031  126.97   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.227 on 9072 degrees of freedom\n#>   (55 observations deleted due to missingness)\n#> Multiple R-squared:  0.6399,\tAdjusted R-squared:  0.6399 \n#> F-statistic: 1.612e+04 on 1 and 9072 DF,  p-value: < 2.2e-16\n\n# Extract the coefficient for pollution\ncoef_naive <- coef(model_naive)[\"pollution\"]\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(df_ca, aes(x = pollution, y = asthma_pct)) +\n  geom_point(alpha = 0.2, size = 0.8, color = \"gray40\") +\n  geom_smooth(method = \"lm\", color = \"red\", se = TRUE, linewidth = 1.2) +\n  labs(\n    title = \"Naive Analysis: Pollution vs. Asthma\",\n    subtitle = \"Without adjusting for neighborhood SES (CONFOUNDED)\",\n    x = \"PM2.5 Pollution (µg/m³)\",\n    y = \"Childhood Asthma Prevalence (%)\"\n  ) +\n  theme_minimal() +\n  annotate(\"text\", x = 16, y = 5,\n           label = paste0(\"Slope = \", round(coef_naive, 3), \" %/µg/m³\"),\n           color = \"red\", size = 4.5, fontface = \"bold\")\n#> `geom_smooth()` using formula = 'y ~ x'\n#> Warning: Removed 55 rows containing non-finite outside the scale range\n#> (`stat_smooth()`).\n#> Warning: Removed 55 rows containing missing values or values outside the scale range\n#> (`geom_point()`).\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/naive_plot-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n**Observation**: The naive estimate is **1.309** %/µg/m³, which is substantially higher than the true effect (0.4 %/µg/m³). This overestimate occurs because the model confounds the effect of pollution with the effect of low SES.\n\n### Step 6: Adjusted Analysis Using Yost Quintiles\n\nNow, let's re-run the analysis while **stratifying by or adjusting for Yost quintiles**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Model 1: Adjust for quintiles as categorical variable\nmodel_quintiles <- lm(asthma_pct ~ pollution + factor(YostImputedQuintile), data = df_ca)\nsummary(model_quintiles)\n#> \n#> Call:\n#> lm(formula = asthma_pct ~ pollution + factor(YostImputedQuintile), \n#>     data = df_ca)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.1541 -0.8059  0.0089  0.8060  4.4036 \n#> \n#> Coefficients:\n#>                                 Estimate Std. Error  t value Pr(>|t|)    \n#> (Intercept)                    6.7356843  0.0885578   76.060   <2e-16 ***\n#> pollution                      0.4051692  0.0084373   48.021   <2e-16 ***\n#> factor(YostImputedQuintile).L -6.1278854  0.0427759 -143.256   <2e-16 ***\n#> factor(YostImputedQuintile).Q  0.9027641  0.0284236   31.761   <2e-16 ***\n#> factor(YostImputedQuintile).C -0.3172845  0.0284224  -11.163   <2e-16 ***\n#> factor(YostImputedQuintile)^4  0.0003652  0.0284238    0.013     0.99    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 1.211 on 9068 degrees of freedom\n#>   (55 observations deleted due to missingness)\n#> Multiple R-squared:  0.8936,\tAdjusted R-squared:  0.8935 \n#> F-statistic: 1.523e+04 on 5 and 9068 DF,  p-value: < 2.2e-16\n\n# Extract coefficients\ncoef_adjusted <- coef(model_quintiles)[\"pollution\"]\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plot pollution vs asthma, colored by quintile\nggplot(df_ca, aes(x = pollution, y = asthma_pct, color = factor(YostImputedQuintile))) +\n  geom_point(alpha = 0.3, size = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 1) +\n  scale_color_viridis_d(\n    name = \"Yost Quintile\",\n    labels = c(\"Q1 (Lowest SES)\", \"Q2\", \"Q3\", \"Q4\", \"Q5 (Highest SES)\")\n  ) +\n  labs(\n    title = \"Adjusted Analysis: Pollution vs. Asthma by SES Quintile\",\n    subtitle = \"Controlling for neighborhood SES reveals the true pollution effect\",\n    x = \"PM2.5 Pollution (µg/m³)\",\n    y = \"Childhood Asthma Prevalence (%)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n#> `geom_smooth()` using formula = 'y ~ x'\n#> Warning: Removed 55 rows containing non-finite outside the scale range\n#> (`stat_smooth()`).\n#> Warning: Removed 55 rows containing missing values or values outside the scale range\n#> (`geom_point()`).\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/adjusted_plot-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n**Result**: After adjusting for Yost quintiles, the estimated pollution effect is **0.405** %/µg/m³, very close to the true value of 0.4 %/µg/m³.\n\n### Step 7: Compare Estimates\n\nLet's create a table and visualization comparing the naive vs. adjusted estimates:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create comparison table\ncomparison <- tibble(\n  Model = c(\"Naive (Unadjusted)\", \"Adjusted for Yost Quintiles\", \"True Effect\"),\n  `Pollution Effect (% per µg/m³)` = c(coef_naive, coef_adjusted, 0.4)\n)\n\nknitr::kable(comparison, digits = 3, caption = \"Comparison of Pollution Effect Estimates\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Pollution Effect Estimates\n\n|Model                       | Pollution Effect (% per µg/m³)|\n|:---------------------------|------------------------------:|\n|Naive (Unadjusted)          |                          1.309|\n|Adjusted for Yost Quintiles |                          0.405|\n|True Effect                 |                          0.400|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(comparison, aes(x = Model, y = `Pollution Effect (% per µg/m³)`)) +\n  geom_col(aes(fill = Model), width = 0.6) +\n  geom_hline(yintercept = 0.4, linetype = \"dashed\", color = \"darkgreen\", linewidth = 1.2) +\n  scale_fill_manual(values = c(\n    \"Naive (Unadjusted)\" = \"coral\",\n    \"Adjusted for Yost Quintiles\" = \"steelblue\",\n    \"True Effect\" = \"darkgreen\"\n  )) +\n  labs(\n    title = \"Effect of PM2.5 on Childhood Asthma: Naive vs. Adjusted\",\n    subtitle = \"Adjusting for Yost quintiles controls for socioeconomic confounding\",\n    y = \"Effect Size (% increase per µg/m³)\",\n    x = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    axis.text.x = element_text(angle = 0, hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](introduction-to-ReproducibleYostIndex_files/figure-html/comparison_plot-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Key Takeaways\n\nThis simulation demonstrates a critical point for observational health research:\n\n1. **Environmental exposures and health outcomes are often both associated with neighborhood SES**\n2. **Failing to account for SES leads to confounded estimates** (in this case, overestimating the pollution effect)\n3. **The Yost Index provides a comprehensive, validated measure of neighborhood SES** that can be used to adjust for socioeconomic confounding\n4. **After adjustment, we obtain a more accurate estimate** of the true causal effect of the exposure on the outcome\n\nIn real-world studies, the Yost Index can be used in regression models, propensity score methods, or stratified analyses to account for the complex role of neighborhood socioeconomic context in shaping health outcomes.\n\n## Conclusion\n\nSocial determinants of health are fundamental drivers of health disparities. The Yost Index provides a robust, validated tool for measuring neighborhood socioeconomic status in health research. The `ReproducibleYostIndex` package makes it easy to obtain Yost Index values instantly via `getYostIndex()` — no Census API key required, with local caching for repeat use.\n\nWhether you're studying environmental health, cancer epidemiology, health services research, or any field where neighborhood context matters, `ReproducibleYostIndex` provides a streamlined, reproducible workflow for incorporating socioeconomic context into your work.\n",
    "supporting": [
      "introduction-to-ReproducibleYostIndex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}